### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by spkelle2**

### CODE REVIEW

**Comment by abdxyz** [comment]
I am very happy to see someone contribute their work. I see that you have implemented the pscost strategy and made the code more systematic.

Do you have a plan for the next development? I plan to implement other algorithms in the future, such as column generation, branch and cut and price.

**Comment by spkelle2** [comment]
Hey nice to meet you!

So my plan with the solver is to use it to test warm starting strategies. I'm adding a cut generating LP so that we can get tight cuts on the underlying LP relaxation and recycle them into restarts of the same or similar MIP solves. I'm excited to see you put together a pricing algorithm. I've always wanted to see what an implementation of that would look like.

Ted really liked how you got the project started, so he thought me building off it for our research would be a good idea. And I agree. It has been really helpful getting a template for how this should be structured in an OOP approach.

**Comment by spkelle2** [comment]
I think Ted is also thinking about using it as a learning tool for his integer programming class to make it a little easier for students to get their hands on adding cutting methods to solvers since python has a little less overhead than C++

**Comment by abdxyz** [comment]
I’m very happy to hear that. Warm start is one of the main motivation when I write the solver. I want to use the basis information of the parent node to accelerate the simplex algorithm of the child node, although I have not finished it. Your contribution motivates me to do this again. 

I also test TSP problems on this solver. After adding lazy cutting, it can solve problem instances up to 100 nodes. I will merge the code to the solver. 

Another problem I care most is the memory, now my code uses a cylp object to represent a child node. When the scale is large, the memory increase continuously and reaches the memory capacity. Do you have some ideas?

**Pull request merged**
